name: Validate manifest

on:
   schedule:
    - cron:  '50 6 * * *'
    
   pull_request:
    branches:
      - main

jobs:
  validation:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    
    - name: Validate node-versions manifest
      shell: pwsh
      run: .\helpers\packages-generation\manifest-validator.ps1 -ManifestUrl https://raw.githubusercontent.com/actions/node-versions/main/versions-manifest.json

  check_build:
    name: Check validation for failures 
    runs-on: ubuntu-latest
    needs: [validation]
    if: success()
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Send Slack notification if validation fails
        shell: pwsh
        run: |
          $message = "The validation of node-versions manifest failed."
          .\helpers\get-new-tool-versions\send-slack-notification.ps1 -Url "${{ secrets.SLACK_CHANNEL_URL }}" `
                                                                      -ToolName "some tool" `
                                                                      -Text "$message" `
                                                                      -ImageUrl "https://golang.org/lib/godoc/images/footer-gopher.jpg"
